/*
 * Argo Server API
 * You can get examples of requests and responses by using the CLI with `--gloglevel=9`, e.g. `argo list --gloglevel=9`
 *
 * The version of the OpenAPI document: v3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.workflow.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * CreateS3BucketOptions options used to determine automatic automatic bucket-creation process
 */
@ApiModel(description = "CreateS3BucketOptions options used to determine automatic automatic bucket-creation process")

public class CreateS3BucketOptions {
  public static final String SERIALIZED_NAME_OBJECT_LOCKING = "objectLocking";
  @SerializedName(SERIALIZED_NAME_OBJECT_LOCKING)
  private Boolean objectLocking;


  public CreateS3BucketOptions objectLocking(Boolean objectLocking) {
    
    this.objectLocking = objectLocking;
    return this;
  }

   /**
   * ObjectLocking Enable object locking
   * @return objectLocking
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "ObjectLocking Enable object locking")

  public Boolean getObjectLocking() {
    return objectLocking;
  }


  public void setObjectLocking(Boolean objectLocking) {
    this.objectLocking = objectLocking;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateS3BucketOptions createS3BucketOptions = (CreateS3BucketOptions) o;
    return Objects.equals(this.objectLocking, createS3BucketOptions.objectLocking);
  }

  @Override
  public int hashCode() {
    return Objects.hash(objectLocking);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateS3BucketOptions {\n");
    sb.append("    objectLocking: ").append(toIndentedString(objectLocking)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

