/*
 * Argo
 * Argo
 *
 * The version of the OpenAPI document: v2.10.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.workflow.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.argoproj.workflow.models.IoArgoprojWorkflowV1alpha1SemaphoreRef;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Synchronization holds synchronization lock configuration
 */
@ApiModel(description = "Synchronization holds synchronization lock configuration")

public class IoArgoprojWorkflowV1alpha1Synchronization {
  public static final String SERIALIZED_NAME_SEMAPHORE = "semaphore";
  @SerializedName(SERIALIZED_NAME_SEMAPHORE)
  private IoArgoprojWorkflowV1alpha1SemaphoreRef semaphore;


  public IoArgoprojWorkflowV1alpha1Synchronization semaphore(IoArgoprojWorkflowV1alpha1SemaphoreRef semaphore) {
    
    this.semaphore = semaphore;
    return this;
  }

   /**
   * Get semaphore
   * @return semaphore
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public IoArgoprojWorkflowV1alpha1SemaphoreRef getSemaphore() {
    return semaphore;
  }


  public void setSemaphore(IoArgoprojWorkflowV1alpha1SemaphoreRef semaphore) {
    this.semaphore = semaphore;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IoArgoprojWorkflowV1alpha1Synchronization ioArgoprojWorkflowV1alpha1Synchronization = (IoArgoprojWorkflowV1alpha1Synchronization) o;
    return Objects.equals(this.semaphore, ioArgoprojWorkflowV1alpha1Synchronization.semaphore);
  }

  @Override
  public int hashCode() {
    return Objects.hash(semaphore);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IoArgoprojWorkflowV1alpha1Synchronization {\n");
    sb.append("    semaphore: ").append(toIndentedString(semaphore)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

