/*
 * Argo
 * Argo
 *
 * The version of the OpenAPI document: v2.9.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.workflow.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Sequence expands a workflow step into numeric range
 */
@ApiModel(description = "Sequence expands a workflow step into numeric range")

public class Sequence {
  public static final String SERIALIZED_NAME_COUNT = "count";
  @SerializedName(SERIALIZED_NAME_COUNT)
  private String count;

  public static final String SERIALIZED_NAME_END = "end";
  @SerializedName(SERIALIZED_NAME_END)
  private String end;

  public static final String SERIALIZED_NAME_FORMAT = "format";
  @SerializedName(SERIALIZED_NAME_FORMAT)
  private String format;

  public static final String SERIALIZED_NAME_START = "start";
  @SerializedName(SERIALIZED_NAME_START)
  private String start;


  public Sequence count(String count) {
    
    this.count = count;
    return this;
  }

   /**
   * Count is number of elements in the sequence (default: 0). Not to be used with end
   * @return count
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Count is number of elements in the sequence (default: 0). Not to be used with end")

  public String getCount() {
    return count;
  }


  public void setCount(String count) {
    this.count = count;
  }


  public Sequence end(String end) {
    
    this.end = end;
    return this;
  }

   /**
   * Number at which to end the sequence (default: 0). Not to be used with Count
   * @return end
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Number at which to end the sequence (default: 0). Not to be used with Count")

  public String getEnd() {
    return end;
  }


  public void setEnd(String end) {
    this.end = end;
  }


  public Sequence format(String format) {
    
    this.format = format;
    return this;
  }

   /**
   * Format is a printf format string to format the value in the sequence
   * @return format
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Format is a printf format string to format the value in the sequence")

  public String getFormat() {
    return format;
  }


  public void setFormat(String format) {
    this.format = format;
  }


  public Sequence start(String start) {
    
    this.start = start;
    return this;
  }

   /**
   * Number at which to start the sequence (default: 0)
   * @return start
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Number at which to start the sequence (default: 0)")

  public String getStart() {
    return start;
  }


  public void setStart(String start) {
    this.start = start;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Sequence sequence = (Sequence) o;
    return Objects.equals(this.count, sequence.count) &&
        Objects.equals(this.end, sequence.end) &&
        Objects.equals(this.format, sequence.format) &&
        Objects.equals(this.start, sequence.start);
  }

  @Override
  public int hashCode() {
    return Objects.hash(count, end, format, start);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Sequence {\n");
    sb.append("    count: ").append(toIndentedString(count)).append("\n");
    sb.append("    end: ").append(toIndentedString(end)).append("\n");
    sb.append("    format: ").append(toIndentedString(format)).append("\n");
    sb.append("    start: ").append(toIndentedString(start)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

