/*
 * Argo Server API
 * You can get examples of requests and responses by using the CLI with `--gloglevel=9`, e.g. `argo list --gloglevel=9`
 *
 * The version of the OpenAPI document: v3.0.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.workflow.apis;

import io.argoproj.workflow.ApiException;
import io.argoproj.workflow.models.GetUserInfoResponse;
import io.argoproj.workflow.models.GrpcGatewayRuntimeError;
import io.argoproj.workflow.models.InfoResponse;
import io.argoproj.workflow.models.Version;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for InfoServiceApi
 */
@Ignore
public class InfoServiceApiTest {

    private final InfoServiceApi api = new InfoServiceApi();

    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void infoServiceGetInfoTest() throws ApiException {
        InfoResponse response = api.infoServiceGetInfo();

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void infoServiceGetUserInfoTest() throws ApiException {
        GetUserInfoResponse response = api.infoServiceGetUserInfo();

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void infoServiceGetVersionTest() throws ApiException {
        Version response = api.infoServiceGetVersion();

        // TODO: test validations
    }
    
}
