/*
 * Argo
 * Argo
 *
 * The version of the OpenAPI document: v2.10.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.openapitools.client.model.IoArgoprojWorkflowV1alpha1Arguments;
import org.openapitools.client.model.IoArgoprojWorkflowV1alpha1ArtifactLocation;
import org.openapitools.client.model.IoArgoprojWorkflowV1alpha1DAGTemplate;
import org.openapitools.client.model.IoArgoprojWorkflowV1alpha1ExecutorConfig;
import org.openapitools.client.model.IoArgoprojWorkflowV1alpha1Inputs;
import org.openapitools.client.model.IoArgoprojWorkflowV1alpha1Metadata;
import org.openapitools.client.model.IoArgoprojWorkflowV1alpha1Metrics;
import org.openapitools.client.model.IoArgoprojWorkflowV1alpha1Outputs;
import org.openapitools.client.model.IoArgoprojWorkflowV1alpha1ParallelSteps;
import org.openapitools.client.model.IoArgoprojWorkflowV1alpha1ResourceTemplate;
import org.openapitools.client.model.IoArgoprojWorkflowV1alpha1RetryStrategy;
import org.openapitools.client.model.IoArgoprojWorkflowV1alpha1ScriptTemplate;
import org.openapitools.client.model.IoArgoprojWorkflowV1alpha1SuspendTemplate;
import org.openapitools.client.model.IoArgoprojWorkflowV1alpha1Synchronization;
import org.openapitools.client.model.IoArgoprojWorkflowV1alpha1TemplateRef;
import org.openapitools.client.model.IoArgoprojWorkflowV1alpha1UserContainer;
import org.openapitools.client.model.IoK8sApiCoreV1Affinity;
import org.openapitools.client.model.IoK8sApiCoreV1Container;
import org.openapitools.client.model.IoK8sApiCoreV1HostAlias;
import org.openapitools.client.model.IoK8sApiCoreV1PodSecurityContext;
import org.openapitools.client.model.IoK8sApiCoreV1Toleration;
import org.openapitools.client.model.IoK8sApiCoreV1Volume;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for IoArgoprojWorkflowV1alpha1Template
 */
public class IoArgoprojWorkflowV1alpha1TemplateTest {
    private final IoArgoprojWorkflowV1alpha1Template model = new IoArgoprojWorkflowV1alpha1Template();

    /**
     * Model tests for IoArgoprojWorkflowV1alpha1Template
     */
    @Test
    public void testIoArgoprojWorkflowV1alpha1Template() {
        // TODO: test IoArgoprojWorkflowV1alpha1Template
    }

    /**
     * Test the property 'activeDeadlineSeconds'
     */
    @Test
    public void activeDeadlineSecondsTest() {
        // TODO: test activeDeadlineSeconds
    }

    /**
     * Test the property 'affinity'
     */
    @Test
    public void affinityTest() {
        // TODO: test affinity
    }

    /**
     * Test the property 'archiveLocation'
     */
    @Test
    public void archiveLocationTest() {
        // TODO: test archiveLocation
    }

    /**
     * Test the property 'arguments'
     */
    @Test
    public void argumentsTest() {
        // TODO: test arguments
    }

    /**
     * Test the property 'automountServiceAccountToken'
     */
    @Test
    public void automountServiceAccountTokenTest() {
        // TODO: test automountServiceAccountToken
    }

    /**
     * Test the property 'container'
     */
    @Test
    public void containerTest() {
        // TODO: test container
    }

    /**
     * Test the property 'daemon'
     */
    @Test
    public void daemonTest() {
        // TODO: test daemon
    }

    /**
     * Test the property 'dag'
     */
    @Test
    public void dagTest() {
        // TODO: test dag
    }

    /**
     * Test the property 'executor'
     */
    @Test
    public void executorTest() {
        // TODO: test executor
    }

    /**
     * Test the property 'hostAliases'
     */
    @Test
    public void hostAliasesTest() {
        // TODO: test hostAliases
    }

    /**
     * Test the property 'initContainers'
     */
    @Test
    public void initContainersTest() {
        // TODO: test initContainers
    }

    /**
     * Test the property 'inputs'
     */
    @Test
    public void inputsTest() {
        // TODO: test inputs
    }

    /**
     * Test the property 'metadata'
     */
    @Test
    public void metadataTest() {
        // TODO: test metadata
    }

    /**
     * Test the property 'metrics'
     */
    @Test
    public void metricsTest() {
        // TODO: test metrics
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'nodeSelector'
     */
    @Test
    public void nodeSelectorTest() {
        // TODO: test nodeSelector
    }

    /**
     * Test the property 'outputs'
     */
    @Test
    public void outputsTest() {
        // TODO: test outputs
    }

    /**
     * Test the property 'parallelism'
     */
    @Test
    public void parallelismTest() {
        // TODO: test parallelism
    }

    /**
     * Test the property 'podSpecPatch'
     */
    @Test
    public void podSpecPatchTest() {
        // TODO: test podSpecPatch
    }

    /**
     * Test the property 'priority'
     */
    @Test
    public void priorityTest() {
        // TODO: test priority
    }

    /**
     * Test the property 'priorityClassName'
     */
    @Test
    public void priorityClassNameTest() {
        // TODO: test priorityClassName
    }

    /**
     * Test the property 'resource'
     */
    @Test
    public void resourceTest() {
        // TODO: test resource
    }

    /**
     * Test the property 'resubmitPendingPods'
     */
    @Test
    public void resubmitPendingPodsTest() {
        // TODO: test resubmitPendingPods
    }

    /**
     * Test the property 'retryStrategy'
     */
    @Test
    public void retryStrategyTest() {
        // TODO: test retryStrategy
    }

    /**
     * Test the property 'schedulerName'
     */
    @Test
    public void schedulerNameTest() {
        // TODO: test schedulerName
    }

    /**
     * Test the property 'script'
     */
    @Test
    public void scriptTest() {
        // TODO: test script
    }

    /**
     * Test the property 'securityContext'
     */
    @Test
    public void securityContextTest() {
        // TODO: test securityContext
    }

    /**
     * Test the property 'serviceAccountName'
     */
    @Test
    public void serviceAccountNameTest() {
        // TODO: test serviceAccountName
    }

    /**
     * Test the property 'sidecars'
     */
    @Test
    public void sidecarsTest() {
        // TODO: test sidecars
    }

    /**
     * Test the property 'steps'
     */
    @Test
    public void stepsTest() {
        // TODO: test steps
    }

    /**
     * Test the property 'suspend'
     */
    @Test
    public void suspendTest() {
        // TODO: test suspend
    }

    /**
     * Test the property 'synchronization'
     */
    @Test
    public void synchronizationTest() {
        // TODO: test synchronization
    }

    /**
     * Test the property 'template'
     */
    @Test
    public void templateTest() {
        // TODO: test template
    }

    /**
     * Test the property 'templateRef'
     */
    @Test
    public void templateRefTest() {
        // TODO: test templateRef
    }

    /**
     * Test the property 'tolerations'
     */
    @Test
    public void tolerationsTest() {
        // TODO: test tolerations
    }

    /**
     * Test the property 'volumes'
     */
    @Test
    public void volumesTest() {
        // TODO: test volumes
    }

}
