/*
 * Argo
 * Argo
 *
 * The version of the OpenAPI document: v2.10.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.IoK8sApiCoreV1ContainerPort;
import org.openapitools.client.model.IoK8sApiCoreV1EnvFromSource;
import org.openapitools.client.model.IoK8sApiCoreV1EnvVar;
import org.openapitools.client.model.IoK8sApiCoreV1Lifecycle;
import org.openapitools.client.model.IoK8sApiCoreV1Probe;
import org.openapitools.client.model.IoK8sApiCoreV1ResourceRequirements;
import org.openapitools.client.model.IoK8sApiCoreV1SecurityContext;
import org.openapitools.client.model.IoK8sApiCoreV1VolumeDevice;
import org.openapitools.client.model.IoK8sApiCoreV1VolumeMount;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for IoArgoprojWorkflowV1alpha1UserContainer
 */
public class IoArgoprojWorkflowV1alpha1UserContainerTest {
    private final IoArgoprojWorkflowV1alpha1UserContainer model = new IoArgoprojWorkflowV1alpha1UserContainer();

    /**
     * Model tests for IoArgoprojWorkflowV1alpha1UserContainer
     */
    @Test
    public void testIoArgoprojWorkflowV1alpha1UserContainer() {
        // TODO: test IoArgoprojWorkflowV1alpha1UserContainer
    }

    /**
     * Test the property 'args'
     */
    @Test
    public void argsTest() {
        // TODO: test args
    }

    /**
     * Test the property 'command'
     */
    @Test
    public void commandTest() {
        // TODO: test command
    }

    /**
     * Test the property 'env'
     */
    @Test
    public void envTest() {
        // TODO: test env
    }

    /**
     * Test the property 'envFrom'
     */
    @Test
    public void envFromTest() {
        // TODO: test envFrom
    }

    /**
     * Test the property 'image'
     */
    @Test
    public void imageTest() {
        // TODO: test image
    }

    /**
     * Test the property 'imagePullPolicy'
     */
    @Test
    public void imagePullPolicyTest() {
        // TODO: test imagePullPolicy
    }

    /**
     * Test the property 'lifecycle'
     */
    @Test
    public void lifecycleTest() {
        // TODO: test lifecycle
    }

    /**
     * Test the property 'livenessProbe'
     */
    @Test
    public void livenessProbeTest() {
        // TODO: test livenessProbe
    }

    /**
     * Test the property 'mirrorVolumeMounts'
     */
    @Test
    public void mirrorVolumeMountsTest() {
        // TODO: test mirrorVolumeMounts
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'ports'
     */
    @Test
    public void portsTest() {
        // TODO: test ports
    }

    /**
     * Test the property 'readinessProbe'
     */
    @Test
    public void readinessProbeTest() {
        // TODO: test readinessProbe
    }

    /**
     * Test the property 'resources'
     */
    @Test
    public void resourcesTest() {
        // TODO: test resources
    }

    /**
     * Test the property 'securityContext'
     */
    @Test
    public void securityContextTest() {
        // TODO: test securityContext
    }

    /**
     * Test the property 'startupProbe'
     */
    @Test
    public void startupProbeTest() {
        // TODO: test startupProbe
    }

    /**
     * Test the property 'stdin'
     */
    @Test
    public void stdinTest() {
        // TODO: test stdin
    }

    /**
     * Test the property 'stdinOnce'
     */
    @Test
    public void stdinOnceTest() {
        // TODO: test stdinOnce
    }

    /**
     * Test the property 'terminationMessagePath'
     */
    @Test
    public void terminationMessagePathTest() {
        // TODO: test terminationMessagePath
    }

    /**
     * Test the property 'terminationMessagePolicy'
     */
    @Test
    public void terminationMessagePolicyTest() {
        // TODO: test terminationMessagePolicy
    }

    /**
     * Test the property 'tty'
     */
    @Test
    public void ttyTest() {
        // TODO: test tty
    }

    /**
     * Test the property 'volumeDevices'
     */
    @Test
    public void volumeDevicesTest() {
        // TODO: test volumeDevices
    }

    /**
     * Test the property 'volumeMounts'
     */
    @Test
    public void volumeMountsTest() {
        // TODO: test volumeMounts
    }

    /**
     * Test the property 'workingDir'
     */
    @Test
    public void workingDirTest() {
        // TODO: test workingDir
    }

}
