/*
 * Argo
 * Argo
 *
 * The version of the OpenAPI document: v2.10.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.IoK8sApiCoreV1SecretKeySelector;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for IoArgoprojWorkflowV1alpha1ArtifactoryArtifact
 */
public class IoArgoprojWorkflowV1alpha1ArtifactoryArtifactTest {
    private final IoArgoprojWorkflowV1alpha1ArtifactoryArtifact model = new IoArgoprojWorkflowV1alpha1ArtifactoryArtifact();

    /**
     * Model tests for IoArgoprojWorkflowV1alpha1ArtifactoryArtifact
     */
    @Test
    public void testIoArgoprojWorkflowV1alpha1ArtifactoryArtifact() {
        // TODO: test IoArgoprojWorkflowV1alpha1ArtifactoryArtifact
    }

    /**
     * Test the property 'passwordSecret'
     */
    @Test
    public void passwordSecretTest() {
        // TODO: test passwordSecret
    }

    /**
     * Test the property 'url'
     */
    @Test
    public void urlTest() {
        // TODO: test url
    }

    /**
     * Test the property 'usernameSecret'
     */
    @Test
    public void usernameSecretTest() {
        // TODO: test usernameSecret
    }

}
