/*
 * Argo
 * Argo
 *
 * The version of the OpenAPI document: v2.10.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for IoArgoprojWorkflowV1alpha1ContinueOn
 */
public class IoArgoprojWorkflowV1alpha1ContinueOnTest {
    private final IoArgoprojWorkflowV1alpha1ContinueOn model = new IoArgoprojWorkflowV1alpha1ContinueOn();

    /**
     * Model tests for IoArgoprojWorkflowV1alpha1ContinueOn
     */
    @Test
    public void testIoArgoprojWorkflowV1alpha1ContinueOn() {
        // TODO: test IoArgoprojWorkflowV1alpha1ContinueOn
    }

    /**
     * Test the property 'error'
     */
    @Test
    public void errorTest() {
        // TODO: test error
    }

    /**
     * Test the property 'failed'
     */
    @Test
    public void failedTest() {
        // TODO: test failed
    }

}
