/*
 * Argo
 * Argo
 *
 * The version of the OpenAPI document: v2.10.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for IoK8sApimachineryPkgApisMetaV1OwnerReference
 */
public class IoK8sApimachineryPkgApisMetaV1OwnerReferenceTest {
    private final IoK8sApimachineryPkgApisMetaV1OwnerReference model = new IoK8sApimachineryPkgApisMetaV1OwnerReference();

    /**
     * Model tests for IoK8sApimachineryPkgApisMetaV1OwnerReference
     */
    @Test
    public void testIoK8sApimachineryPkgApisMetaV1OwnerReference() {
        // TODO: test IoK8sApimachineryPkgApisMetaV1OwnerReference
    }

    /**
     * Test the property 'apiVersion'
     */
    @Test
    public void apiVersionTest() {
        // TODO: test apiVersion
    }

    /**
     * Test the property 'blockOwnerDeletion'
     */
    @Test
    public void blockOwnerDeletionTest() {
        // TODO: test blockOwnerDeletion
    }

    /**
     * Test the property 'controller'
     */
    @Test
    public void controllerTest() {
        // TODO: test controller
    }

    /**
     * Test the property 'kind'
     */
    @Test
    public void kindTest() {
        // TODO: test kind
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'uid'
     */
    @Test
    public void uidTest() {
        // TODO: test uid
    }

}
