/*
 * Argo
 * Argo
 *
 * The version of the OpenAPI document: v2.10.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.IoK8sApiCoreV1PodAffinityTerm;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for IoK8sApiCoreV1WeightedPodAffinityTerm
 */
public class IoK8sApiCoreV1WeightedPodAffinityTermTest {
    private final IoK8sApiCoreV1WeightedPodAffinityTerm model = new IoK8sApiCoreV1WeightedPodAffinityTerm();

    /**
     * Model tests for IoK8sApiCoreV1WeightedPodAffinityTerm
     */
    @Test
    public void testIoK8sApiCoreV1WeightedPodAffinityTerm() {
        // TODO: test IoK8sApiCoreV1WeightedPodAffinityTerm
    }

    /**
     * Test the property 'podAffinityTerm'
     */
    @Test
    public void podAffinityTermTest() {
        // TODO: test podAffinityTerm
    }

    /**
     * Test the property 'weight'
     */
    @Test
    public void weightTest() {
        // TODO: test weight
    }

}
