/*
 * Argo Server API
 * You can get examples of requests and responses by using the CLI with `--gloglevel=9`, e.g. `argo list --gloglevel=9`
 *
 * The version of the OpenAPI document: v2.12.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.workflow.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.argoproj.workflow.models.ArtifactoryArtifact;
import io.argoproj.workflow.models.GCSArtifact;
import io.argoproj.workflow.models.GitArtifact;
import io.argoproj.workflow.models.HDFSArtifact;
import io.argoproj.workflow.models.HTTPArtifact;
import io.argoproj.workflow.models.OSSArtifact;
import io.argoproj.workflow.models.RawArtifact;
import io.argoproj.workflow.models.S3Artifact;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ArtifactLocation
 */
public class ArtifactLocationTest {
    private final ArtifactLocation model = new ArtifactLocation();

    /**
     * Model tests for ArtifactLocation
     */
    @Test
    public void testArtifactLocation() {
        // TODO: test ArtifactLocation
    }

    /**
     * Test the property 'archiveLogs'
     */
    @Test
    public void archiveLogsTest() {
        // TODO: test archiveLogs
    }

    /**
     * Test the property 'artifactory'
     */
    @Test
    public void artifactoryTest() {
        // TODO: test artifactory
    }

    /**
     * Test the property 'gcs'
     */
    @Test
    public void gcsTest() {
        // TODO: test gcs
    }

    /**
     * Test the property 'git'
     */
    @Test
    public void gitTest() {
        // TODO: test git
    }

    /**
     * Test the property 'hdfs'
     */
    @Test
    public void hdfsTest() {
        // TODO: test hdfs
    }

    /**
     * Test the property 'http'
     */
    @Test
    public void httpTest() {
        // TODO: test http
    }

    /**
     * Test the property 'oss'
     */
    @Test
    public void ossTest() {
        // TODO: test oss
    }

    /**
     * Test the property 'raw'
     */
    @Test
    public void rawTest() {
        // TODO: test raw
    }

    /**
     * Test the property 's3'
     */
    @Test
    public void s3Test() {
        // TODO: test s3
    }

}
