/*
 * Argo
 * Argo
 *
 * The version of the OpenAPI document: v2.10.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.workflow.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ArtifactRepositoryRef
 */
public class ArtifactRepositoryRefTest {
    private final ArtifactRepositoryRef model = new ArtifactRepositoryRef();

    /**
     * Model tests for ArtifactRepositoryRef
     */
    @Test
    public void testArtifactRepositoryRef() {
        // TODO: test ArtifactRepositoryRef
    }

    /**
     * Test the property 'configMap'
     */
    @Test
    public void configMapTest() {
        // TODO: test configMap
    }

    /**
     * Test the property 'key'
     */
    @Test
    public void keyTest() {
        // TODO: test key
    }

}
