/*
 * Argo Server API
 * You can get examples of requests and responses by using the CLI with `--gloglevel=9`, e.g. `argo list --gloglevel=9`
 *
 * The version of the OpenAPI document: v2.12.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.workflow.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.argoproj.workflow.models.CreateOptions;
import io.argoproj.workflow.models.CronWorkflow;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for CreateCronWorkflowRequest
 */
public class CreateCronWorkflowRequestTest {
    private final CreateCronWorkflowRequest model = new CreateCronWorkflowRequest();

    /**
     * Model tests for CreateCronWorkflowRequest
     */
    @Test
    public void testCreateCronWorkflowRequest() {
        // TODO: test CreateCronWorkflowRequest
    }

    /**
     * Test the property 'createOptions'
     */
    @Test
    public void createOptionsTest() {
        // TODO: test createOptions
    }

    /**
     * Test the property 'cronWorkflow'
     */
    @Test
    public void cronWorkflowTest() {
        // TODO: test cronWorkflow
    }

    /**
     * Test the property 'namespace'
     */
    @Test
    public void namespaceTest() {
        // TODO: test namespace
    }

}
