/*
 * Argo Server API
 * You can get examples of requests and responses by using the CLI with `--gloglevel=9`, e.g. `argo list --gloglevel=9`
 *
 * The version of the OpenAPI document: v3.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.workflow.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.argoproj.workflow.models.IoArgoprojEventsV1alpha1CatchupConfiguration;
import io.argoproj.workflow.models.IoArgoprojEventsV1alpha1ConfigMapPersistence;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for IoArgoprojEventsV1alpha1EventPersistence
 */
public class IoArgoprojEventsV1alpha1EventPersistenceTest {
    private final IoArgoprojEventsV1alpha1EventPersistence model = new IoArgoprojEventsV1alpha1EventPersistence();

    /**
     * Model tests for IoArgoprojEventsV1alpha1EventPersistence
     */
    @Test
    public void testIoArgoprojEventsV1alpha1EventPersistence() {
        // TODO: test IoArgoprojEventsV1alpha1EventPersistence
    }

    /**
     * Test the property 'catchup'
     */
    @Test
    public void catchupTest() {
        // TODO: test catchup
    }

    /**
     * Test the property 'configMap'
     */
    @Test
    public void configMapTest() {
        // TODO: test configMap
    }

}
