/*
 * Argo
 * Argo
 *
 * The version of the OpenAPI document: v2.10.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.workflow.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.argoproj.workflow.models.IoArgoprojWorkflowV1alpha1Condition;
import io.argoproj.workflow.models.IoArgoprojWorkflowV1alpha1NodeStatus;
import io.argoproj.workflow.models.IoArgoprojWorkflowV1alpha1Outputs;
import io.argoproj.workflow.models.IoArgoprojWorkflowV1alpha1SynchronizationStatus;
import io.argoproj.workflow.models.IoArgoprojWorkflowV1alpha1Template;
import io.argoproj.workflow.models.IoArgoprojWorkflowV1alpha1WorkflowSpec;
import io.argoproj.workflow.models.IoK8sApiCoreV1Volume;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.joda.time.DateTime;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for IoArgoprojWorkflowV1alpha1WorkflowStatus
 */
public class IoArgoprojWorkflowV1alpha1WorkflowStatusTest {
    private final IoArgoprojWorkflowV1alpha1WorkflowStatus model = new IoArgoprojWorkflowV1alpha1WorkflowStatus();

    /**
     * Model tests for IoArgoprojWorkflowV1alpha1WorkflowStatus
     */
    @Test
    public void testIoArgoprojWorkflowV1alpha1WorkflowStatus() {
        // TODO: test IoArgoprojWorkflowV1alpha1WorkflowStatus
    }

    /**
     * Test the property 'compressedNodes'
     */
    @Test
    public void compressedNodesTest() {
        // TODO: test compressedNodes
    }

    /**
     * Test the property 'conditions'
     */
    @Test
    public void conditionsTest() {
        // TODO: test conditions
    }

    /**
     * Test the property 'finishedAt'
     */
    @Test
    public void finishedAtTest() {
        // TODO: test finishedAt
    }

    /**
     * Test the property 'message'
     */
    @Test
    public void messageTest() {
        // TODO: test message
    }

    /**
     * Test the property 'nodes'
     */
    @Test
    public void nodesTest() {
        // TODO: test nodes
    }

    /**
     * Test the property 'offloadNodeStatusVersion'
     */
    @Test
    public void offloadNodeStatusVersionTest() {
        // TODO: test offloadNodeStatusVersion
    }

    /**
     * Test the property 'outputs'
     */
    @Test
    public void outputsTest() {
        // TODO: test outputs
    }

    /**
     * Test the property 'persistentVolumeClaims'
     */
    @Test
    public void persistentVolumeClaimsTest() {
        // TODO: test persistentVolumeClaims
    }

    /**
     * Test the property 'phase'
     */
    @Test
    public void phaseTest() {
        // TODO: test phase
    }

    /**
     * Test the property 'resourcesDuration'
     */
    @Test
    public void resourcesDurationTest() {
        // TODO: test resourcesDuration
    }

    /**
     * Test the property 'startedAt'
     */
    @Test
    public void startedAtTest() {
        // TODO: test startedAt
    }

    /**
     * Test the property 'storedTemplates'
     */
    @Test
    public void storedTemplatesTest() {
        // TODO: test storedTemplates
    }

    /**
     * Test the property 'storedWorkflowTemplateSpec'
     */
    @Test
    public void storedWorkflowTemplateSpecTest() {
        // TODO: test storedWorkflowTemplateSpec
    }

    /**
     * Test the property 'synchronization'
     */
    @Test
    public void synchronizationTest() {
        // TODO: test synchronization
    }

}
