/*
 * Argo
 * Argo
 *
 * The version of the OpenAPI document: v2.10.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.workflow.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.argoproj.workflow.models.IoArgoprojWorkflowV1alpha1WorkflowTemplate;
import io.argoproj.workflow.models.IoK8sApimachineryPkgApisMetaV1CreateOptions;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for IoArgoprojWorkflowV1alpha1WorkflowTemplateLintRequest
 */
public class IoArgoprojWorkflowV1alpha1WorkflowTemplateLintRequestTest {
    private final IoArgoprojWorkflowV1alpha1WorkflowTemplateLintRequest model = new IoArgoprojWorkflowV1alpha1WorkflowTemplateLintRequest();

    /**
     * Model tests for IoArgoprojWorkflowV1alpha1WorkflowTemplateLintRequest
     */
    @Test
    public void testIoArgoprojWorkflowV1alpha1WorkflowTemplateLintRequest() {
        // TODO: test IoArgoprojWorkflowV1alpha1WorkflowTemplateLintRequest
    }

    /**
     * Test the property 'createOptions'
     */
    @Test
    public void createOptionsTest() {
        // TODO: test createOptions
    }

    /**
     * Test the property 'namespace'
     */
    @Test
    public void namespaceTest() {
        // TODO: test namespace
    }

    /**
     * Test the property 'template'
     */
    @Test
    public void templateTest() {
        // TODO: test template
    }

}
