/*
 * Argo Server API
 * You can get examples of requests and responses by using the CLI with `--gloglevel=9`, e.g. `argo list --gloglevel=9`
 *
 * The version of the OpenAPI document: v3.0.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.workflow.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.argoproj.workflow.models.IoArgoprojEventsV1alpha1Amount;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for IoArgoprojEventsV1alpha1Backoff
 */
public class IoArgoprojEventsV1alpha1BackoffTest {
    private final IoArgoprojEventsV1alpha1Backoff model = new IoArgoprojEventsV1alpha1Backoff();

    /**
     * Model tests for IoArgoprojEventsV1alpha1Backoff
     */
    @Test
    public void testIoArgoprojEventsV1alpha1Backoff() {
        // TODO: test IoArgoprojEventsV1alpha1Backoff
    }

    /**
     * Test the property 'duration'
     */
    @Test
    public void durationTest() {
        // TODO: test duration
    }

    /**
     * Test the property 'factor'
     */
    @Test
    public void factorTest() {
        // TODO: test factor
    }

    /**
     * Test the property 'jitter'
     */
    @Test
    public void jitterTest() {
        // TODO: test jitter
    }

    /**
     * Test the property 'steps'
     */
    @Test
    public void stepsTest() {
        // TODO: test steps
    }

}
