/*
 * Argo Server API
 * You can get examples of requests and responses by using the CLI with `--gloglevel=9`, e.g. `argo list --gloglevel=9`
 *
 * The version of the OpenAPI document: v3.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.workflow.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.argoproj.workflow.models.IoArgoprojEventsV1alpha1Backoff;
import io.argoproj.workflow.models.IoArgoprojEventsV1alpha1TLSConfig;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for IoArgoprojEventsV1alpha1EmitterEventSource
 */
public class IoArgoprojEventsV1alpha1EmitterEventSourceTest {
    private final IoArgoprojEventsV1alpha1EmitterEventSource model = new IoArgoprojEventsV1alpha1EmitterEventSource();

    /**
     * Model tests for IoArgoprojEventsV1alpha1EmitterEventSource
     */
    @Test
    public void testIoArgoprojEventsV1alpha1EmitterEventSource() {
        // TODO: test IoArgoprojEventsV1alpha1EmitterEventSource
    }

    /**
     * Test the property 'broker'
     */
    @Test
    public void brokerTest() {
        // TODO: test broker
    }

    /**
     * Test the property 'channelKey'
     */
    @Test
    public void channelKeyTest() {
        // TODO: test channelKey
    }

    /**
     * Test the property 'channelName'
     */
    @Test
    public void channelNameTest() {
        // TODO: test channelName
    }

    /**
     * Test the property 'connectionBackoff'
     */
    @Test
    public void connectionBackoffTest() {
        // TODO: test connectionBackoff
    }

    /**
     * Test the property 'jsonBody'
     */
    @Test
    public void jsonBodyTest() {
        // TODO: test jsonBody
    }

    /**
     * Test the property 'metadata'
     */
    @Test
    public void metadataTest() {
        // TODO: test metadata
    }

    /**
     * Test the property 'password'
     */
    @Test
    public void passwordTest() {
        // TODO: test password
    }

    /**
     * Test the property 'tls'
     */
    @Test
    public void tlsTest() {
        // TODO: test tls
    }

    /**
     * Test the property 'username'
     */
    @Test
    public void usernameTest() {
        // TODO: test username
    }

}
