/*
 * Argo Server API
 * You can get examples of requests and responses by using the CLI with `--gloglevel=9`, e.g. `argo list --gloglevel=9`
 *
 * The version of the OpenAPI document: v3.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.workflow.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for IoArgoprojEventsV1alpha1URLArtifact
 */
public class IoArgoprojEventsV1alpha1URLArtifactTest {
    private final IoArgoprojEventsV1alpha1URLArtifact model = new IoArgoprojEventsV1alpha1URLArtifact();

    /**
     * Model tests for IoArgoprojEventsV1alpha1URLArtifact
     */
    @Test
    public void testIoArgoprojEventsV1alpha1URLArtifact() {
        // TODO: test IoArgoprojEventsV1alpha1URLArtifact
    }

    /**
     * Test the property 'path'
     */
    @Test
    public void pathTest() {
        // TODO: test path
    }

    /**
     * Test the property 'verifyCert'
     */
    @Test
    public void verifyCertTest() {
        // TODO: test verifyCert
    }

}
