/*
 * Argo
 * Argo
 *
 * The version of the OpenAPI document: v2.10.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.workflow.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.argoproj.workflow.models.IoArgoprojWorkflowV1alpha1Prometheus;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for IoArgoprojWorkflowV1alpha1Metrics
 */
public class IoArgoprojWorkflowV1alpha1MetricsTest {
    private final IoArgoprojWorkflowV1alpha1Metrics model = new IoArgoprojWorkflowV1alpha1Metrics();

    /**
     * Model tests for IoArgoprojWorkflowV1alpha1Metrics
     */
    @Test
    public void testIoArgoprojWorkflowV1alpha1Metrics() {
        // TODO: test IoArgoprojWorkflowV1alpha1Metrics
    }

    /**
     * Test the property 'prometheus'
     */
    @Test
    public void prometheusTest() {
        // TODO: test prometheus
    }

}
