/*
 * Argo Server API
 * You can get examples of requests and responses by using the CLI with `--gloglevel=9`, e.g. `argo list --gloglevel=9`
 *
 * The version of the OpenAPI document: v3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.workflow.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for IoArgoprojEventsV1alpha1EventContext
 */
public class IoArgoprojEventsV1alpha1EventContextTest {
    private final IoArgoprojEventsV1alpha1EventContext model = new IoArgoprojEventsV1alpha1EventContext();

    /**
     * Model tests for IoArgoprojEventsV1alpha1EventContext
     */
    @Test
    public void testIoArgoprojEventsV1alpha1EventContext() {
        // TODO: test IoArgoprojEventsV1alpha1EventContext
    }

    /**
     * Test the property 'datacontenttype'
     */
    @Test
    public void datacontenttypeTest() {
        // TODO: test datacontenttype
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'source'
     */
    @Test
    public void sourceTest() {
        // TODO: test source
    }

    /**
     * Test the property 'specversion'
     */
    @Test
    public void specversionTest() {
        // TODO: test specversion
    }

    /**
     * Test the property 'subject'
     */
    @Test
    public void subjectTest() {
        // TODO: test subject
    }

    /**
     * Test the property 'time'
     */
    @Test
    public void timeTest() {
        // TODO: test time
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

}
