/*
 * Argo
 * Argo
 *
 * The version of the OpenAPI document: v2.10.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.workflow.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.argoproj.workflow.models.IoK8sApiCoreV1NodeSelectorTerm;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for IoK8sApiCoreV1NodeSelector
 */
public class IoK8sApiCoreV1NodeSelectorTest {
    private final IoK8sApiCoreV1NodeSelector model = new IoK8sApiCoreV1NodeSelector();

    /**
     * Model tests for IoK8sApiCoreV1NodeSelector
     */
    @Test
    public void testIoK8sApiCoreV1NodeSelector() {
        // TODO: test IoK8sApiCoreV1NodeSelector
    }

    /**
     * Test the property 'nodeSelectorTerms'
     */
    @Test
    public void nodeSelectorTermsTest() {
        // TODO: test nodeSelectorTerms
    }

}
