/*
 * Argo
 * Argo
 *
 * The version of the OpenAPI document: v2.10.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.workflow.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for IoK8sApimachineryPkgApisMetaV1StatusCause
 */
public class IoK8sApimachineryPkgApisMetaV1StatusCauseTest {
    private final IoK8sApimachineryPkgApisMetaV1StatusCause model = new IoK8sApimachineryPkgApisMetaV1StatusCause();

    /**
     * Model tests for IoK8sApimachineryPkgApisMetaV1StatusCause
     */
    @Test
    public void testIoK8sApimachineryPkgApisMetaV1StatusCause() {
        // TODO: test IoK8sApimachineryPkgApisMetaV1StatusCause
    }

    /**
     * Test the property 'field'
     */
    @Test
    public void fieldTest() {
        // TODO: test field
    }

    /**
     * Test the property 'message'
     */
    @Test
    public void messageTest() {
        // TODO: test message
    }

    /**
     * Test the property 'reason'
     */
    @Test
    public void reasonTest() {
        // TODO: test reason
    }

}
