/*
 * Argo
 * Argo
 *
 * The version of the OpenAPI document: v2.10.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.workflow.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.argoproj.workflow.models.IoK8sApiCoreV1ExecAction;
import io.argoproj.workflow.models.IoK8sApiCoreV1HTTPGetAction;
import io.argoproj.workflow.models.IoK8sApiCoreV1TCPSocketAction;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for IoK8sApiCoreV1Handler
 */
public class IoK8sApiCoreV1HandlerTest {
    private final IoK8sApiCoreV1Handler model = new IoK8sApiCoreV1Handler();

    /**
     * Model tests for IoK8sApiCoreV1Handler
     */
    @Test
    public void testIoK8sApiCoreV1Handler() {
        // TODO: test IoK8sApiCoreV1Handler
    }

    /**
     * Test the property 'exec'
     */
    @Test
    public void execTest() {
        // TODO: test exec
    }

    /**
     * Test the property 'httpGet'
     */
    @Test
    public void httpGetTest() {
        // TODO: test httpGet
    }

    /**
     * Test the property 'tcpSocket'
     */
    @Test
    public void tcpSocketTest() {
        // TODO: test tcpSocket
    }

}
