/*
 * Argo
 * Argo
 *
 * The version of the OpenAPI document: v2.10.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.workflow.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for IoK8sApimachineryPkgApisMetaV1ListMeta
 */
public class IoK8sApimachineryPkgApisMetaV1ListMetaTest {
    private final IoK8sApimachineryPkgApisMetaV1ListMeta model = new IoK8sApimachineryPkgApisMetaV1ListMeta();

    /**
     * Model tests for IoK8sApimachineryPkgApisMetaV1ListMeta
     */
    @Test
    public void testIoK8sApimachineryPkgApisMetaV1ListMeta() {
        // TODO: test IoK8sApimachineryPkgApisMetaV1ListMeta
    }

    /**
     * Test the property '_continue'
     */
    @Test
    public void _continueTest() {
        // TODO: test _continue
    }

    /**
     * Test the property 'remainingItemCount'
     */
    @Test
    public void remainingItemCountTest() {
        // TODO: test remainingItemCount
    }

    /**
     * Test the property 'resourceVersion'
     */
    @Test
    public void resourceVersionTest() {
        // TODO: test resourceVersion
    }

    /**
     * Test the property 'selfLink'
     */
    @Test
    public void selfLinkTest() {
        // TODO: test selfLink
    }

}
