/*
 * Argo
 * Argo
 *
 * The version of the OpenAPI document: v2.10.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.workflow.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for IoK8sApiCoreV1AzureDiskVolumeSource
 */
public class IoK8sApiCoreV1AzureDiskVolumeSourceTest {
    private final IoK8sApiCoreV1AzureDiskVolumeSource model = new IoK8sApiCoreV1AzureDiskVolumeSource();

    /**
     * Model tests for IoK8sApiCoreV1AzureDiskVolumeSource
     */
    @Test
    public void testIoK8sApiCoreV1AzureDiskVolumeSource() {
        // TODO: test IoK8sApiCoreV1AzureDiskVolumeSource
    }

    /**
     * Test the property 'cachingMode'
     */
    @Test
    public void cachingModeTest() {
        // TODO: test cachingMode
    }

    /**
     * Test the property 'diskName'
     */
    @Test
    public void diskNameTest() {
        // TODO: test diskName
    }

    /**
     * Test the property 'diskURI'
     */
    @Test
    public void diskURITest() {
        // TODO: test diskURI
    }

    /**
     * Test the property 'fsType'
     */
    @Test
    public void fsTypeTest() {
        // TODO: test fsType
    }

    /**
     * Test the property 'kind'
     */
    @Test
    public void kindTest() {
        // TODO: test kind
    }

    /**
     * Test the property 'readOnly'
     */
    @Test
    public void readOnlyTest() {
        // TODO: test readOnly
    }

}
