/*
 * Argo
 * Argo
 *
 * The version of the OpenAPI document: v2.10.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.workflow.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for IoK8sApiCoreV1LocalObjectReference
 */
public class IoK8sApiCoreV1LocalObjectReferenceTest {
    private final IoK8sApiCoreV1LocalObjectReference model = new IoK8sApiCoreV1LocalObjectReference();

    /**
     * Model tests for IoK8sApiCoreV1LocalObjectReference
     */
    @Test
    public void testIoK8sApiCoreV1LocalObjectReference() {
        // TODO: test IoK8sApiCoreV1LocalObjectReference
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

}
