/*
 * Argo
 * Argo
 *
 * The version of the OpenAPI document: v2.10.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.workflow.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.argoproj.workflow.models.IoK8sApiCoreV1Handler;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for IoK8sApiCoreV1Lifecycle
 */
public class IoK8sApiCoreV1LifecycleTest {
    private final IoK8sApiCoreV1Lifecycle model = new IoK8sApiCoreV1Lifecycle();

    /**
     * Model tests for IoK8sApiCoreV1Lifecycle
     */
    @Test
    public void testIoK8sApiCoreV1Lifecycle() {
        // TODO: test IoK8sApiCoreV1Lifecycle
    }

    /**
     * Test the property 'postStart'
     */
    @Test
    public void postStartTest() {
        // TODO: test postStart
    }

    /**
     * Test the property 'preStop'
     */
    @Test
    public void preStopTest() {
        // TODO: test preStop
    }

}
