/*
 * Argo
 * Argo
 *
 * The version of the OpenAPI document: v2.10.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.workflow.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for IoK8sApiCoreV1HostAlias
 */
public class IoK8sApiCoreV1HostAliasTest {
    private final IoK8sApiCoreV1HostAlias model = new IoK8sApiCoreV1HostAlias();

    /**
     * Model tests for IoK8sApiCoreV1HostAlias
     */
    @Test
    public void testIoK8sApiCoreV1HostAlias() {
        // TODO: test IoK8sApiCoreV1HostAlias
    }

    /**
     * Test the property 'hostnames'
     */
    @Test
    public void hostnamesTest() {
        // TODO: test hostnames
    }

    /**
     * Test the property 'ip'
     */
    @Test
    public void ipTest() {
        // TODO: test ip
    }

}
