/*
 * Argo Server API
 * You can get examples of requests and responses by using the CLI with `--gloglevel=9`, e.g. `argo list --gloglevel=9`
 *
 * The version of the OpenAPI document: v2.11.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.workflow.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for S3Artifact
 */
public class S3ArtifactTest {
    private final S3Artifact model = new S3Artifact();

    /**
     * Model tests for S3Artifact
     */
    @Test
    public void testS3Artifact() {
        // TODO: test S3Artifact
    }

    /**
     * Test the property 'accessKeySecret'
     */
    @Test
    public void accessKeySecretTest() {
        // TODO: test accessKeySecret
    }

    /**
     * Test the property 'bucket'
     */
    @Test
    public void bucketTest() {
        // TODO: test bucket
    }

    /**
     * Test the property 'endpoint'
     */
    @Test
    public void endpointTest() {
        // TODO: test endpoint
    }

    /**
     * Test the property 'insecure'
     */
    @Test
    public void insecureTest() {
        // TODO: test insecure
    }

    /**
     * Test the property 'key'
     */
    @Test
    public void keyTest() {
        // TODO: test key
    }

    /**
     * Test the property 'region'
     */
    @Test
    public void regionTest() {
        // TODO: test region
    }

    /**
     * Test the property 'roleARN'
     */
    @Test
    public void roleARNTest() {
        // TODO: test roleARN
    }

    /**
     * Test the property 'secretKeySecret'
     */
    @Test
    public void secretKeySecretTest() {
        // TODO: test secretKeySecret
    }

    /**
     * Test the property 'useSDKCreds'
     */
    @Test
    public void useSDKCredsTest() {
        // TODO: test useSDKCreds
    }

}
