/*
 * Argo Server API
 * You can get examples of requests and responses by using the CLI with `--gloglevel=9`, e.g. `argo list --gloglevel=9`
 *
 * The version of the OpenAPI document: v2.11.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.workflow.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.argoproj.workflow.models.SemaphoreHolding;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for SemaphoreStatus
 */
public class SemaphoreStatusTest {
    private final SemaphoreStatus model = new SemaphoreStatus();

    /**
     * Model tests for SemaphoreStatus
     */
    @Test
    public void testSemaphoreStatus() {
        // TODO: test SemaphoreStatus
    }

    /**
     * Test the property 'holding'
     */
    @Test
    public void holdingTest() {
        // TODO: test holding
    }

    /**
     * Test the property 'waiting'
     */
    @Test
    public void waitingTest() {
        // TODO: test waiting
    }

}
