/*
 * Argo Server API
 * You can get examples of requests and responses by using the CLI with `--gloglevel=9`, e.g. `argo list --gloglevel=9`
 *
 * The version of the OpenAPI document: v2.11.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.workflow.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for TTLStrategy
 */
public class TTLStrategyTest {
    private final TTLStrategy model = new TTLStrategy();

    /**
     * Model tests for TTLStrategy
     */
    @Test
    public void testTTLStrategy() {
        // TODO: test TTLStrategy
    }

    /**
     * Test the property 'secondsAfterCompletion'
     */
    @Test
    public void secondsAfterCompletionTest() {
        // TODO: test secondsAfterCompletion
    }

    /**
     * Test the property 'secondsAfterFailure'
     */
    @Test
    public void secondsAfterFailureTest() {
        // TODO: test secondsAfterFailure
    }

    /**
     * Test the property 'secondsAfterSuccess'
     */
    @Test
    public void secondsAfterSuccessTest() {
        // TODO: test secondsAfterSuccess
    }

}
