/*
 * Argo
 * Argo
 *
 * The version of the OpenAPI document: v2.10.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.workflow.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.argoproj.workflow.models.PodAffinityTerm;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for WeightedPodAffinityTerm
 */
public class WeightedPodAffinityTermTest {
    private final WeightedPodAffinityTerm model = new WeightedPodAffinityTerm();

    /**
     * Model tests for WeightedPodAffinityTerm
     */
    @Test
    public void testWeightedPodAffinityTerm() {
        // TODO: test WeightedPodAffinityTerm
    }

    /**
     * Test the property 'podAffinityTerm'
     */
    @Test
    public void podAffinityTermTest() {
        // TODO: test podAffinityTerm
    }

    /**
     * Test the property 'weight'
     */
    @Test
    public void weightTest() {
        // TODO: test weight
    }

}
